# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "DevFest 2014"
email: "devfest@gdg.com.ar"
description: "Los DevFest son un conjunto de eventos tecnicos alrededor del mundo"
baseurl: "/zeppelin"
url: "http://gdg-x.github.io"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-27211040-9"
#googleAnalyticsSiteUrl: "devfest.gdg.com.ar"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Baires"
organizerAlternateName: "Google Developer Group - BsAs - Cordoba - Santa Fe"
organizerDescription: "Comunidades de desarrolladores de Argentina a las que nos apasiona la tecnología y construimos productos innovadores con tecnologías Google."
organizerEmail: "devfest@gdg.com.ar"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.gdg.com.ar/"

# Head
metaKeywords: "event, gdg, devfest, google, programacion, desarrolladores,programming, android, chrome, developers, lviv"
twitterAccount: "@gdgbsas"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "http://bit.ly/dfua-c4p"
#c4sponsorsUrl: "mailto:devfest@gdg.com.ar?subject=Sponsor%20Devfest2014"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {link: "https://plus.google.com/u/0/events/coi0oe0cn0avk6qun0pnt3849vs", text: "G+event"}
# - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Oradores"}
 - {permalink: "/team/", text: "Equipo"}
# - {permalink: "/logistics/", text: "Logistica"}
 - {permalink: "/hackathon/", text: "WorkShop"}
bottomNavigationLinks:
# - {link: "http://bit.ly/dfua-c4p", text: "Se un orador"}
rightNavigationButtons:
# - {link: "http://bit.ly/dfua-c4p", text: "Se un orador"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "6 Diciembre 2014"
typeoutTextValues: '"Argentina"'
typeoutFallback: "AR"
heroButtons:
# - {link: "http://bit.ly/dfua-c4p", text: "Se un orador"}
 - {link: "https://eventioz.com.ar/e/devfest-2014", text: "Registro"}

# About Block
aboutTitle: "Acerca del DevFest"
aboutBlock:
 - {title: "Charlas", image: "conference.jpg", text: "El mayor evento sobre tecnología Google del país, cuidadosamente elaborado por las comunidads GDG! Espectaculares expositores y mucha diversión!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Un día completo de talleres, donde te nos ensuciamos las manos de coding, hacking and debugging. Vení a experimentar con tu tecnología preferida!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day free-style hackaton! sumate!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "500", specialCharacter: "+", info: "desarrolladores", detail: "de todas partes"}
 - {count: "20", specialCharacter: "+", info: "horas", detail: " de tecnologías Google"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "de nuestro país y el exterior"}
 - {count: "4", specialCharacter: "", info: "tracks paralelos", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Novedades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "Centro Cultural San Martín"
eventLocationLink: "http://elculturalsanmartin.org/"
eventStreetAddress: "Sarmiento 1551"
eventAddressLocality: "Buenos Aires"
eventAddressLocalityRegion: "Buenos Aires"
eventPostalCode: "79000"
eventAddressCountry: "Argentina"
eventStartTime: "2014-06-12T10:45"
eventDoorTime: "09:00"
eventEndTime: "2014-06-12T18:30"
eventPlaceCoordinates: "-34.604886, -58.388366"
mapCenterCoordinates: "-34.604886, -58.388366"
mapMobileCenterCoordinates: "-34.604886, -58.388366"

# Venue Block
venueBlockTitle: "Locación"
venueBigImage: "ccgsm_1.jpg"
venueSmallImage1: "ccgsm.png"
venueSmallImage2: "ccgsm_4.jpg"
venueTitle: "Centro Cultural San Martín"
venueFeatures: ["4 salas totalmente equipadas", "Espacio común con varias sorpresas", "Ubicado en el centro de la ciudad"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Queres saber más?"
twitterHashTag: "DevFestArg"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Quiero ser sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://eepurl.com/kOXDX"
subscribeInfo: "La inscripción estará abierta pronto. El número de entradas es limitado. Manténte al tanto!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Las entradas permiten el acceso a todas las secciones de la conferencia, coffee brakes, el almuerzo y la fiesta. El alojamiento no está incluido en el precio del ticket."
ticketsOffers:
 -
  name: "Early Bird"
  price: "0"
  priceCurrency: "ARS"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Registrarse"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "0"
  priceCurrency: "ARS"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Registrarse"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-11-01T00:00"
  validThrough: "2014-11-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "0"
  priceCurrency: "ARS"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Registrarse"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://www.google.com/+gtugar", icon: "google-plus"}
 - {link: "https://twitter.com/gdgbsas", icon: "twitter"}
 - {link: "https://www.facebook.com/groups/gtug.bsas/", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.gdg.com.ar", text: "GDG Buenos Aires"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:devfest@gdg.com.ar", text: "devfest@gdg.com.ar"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "Quiénes somos"
aboutUs: "El DevFest es un evento anual a gran escala, dirigidos por la comunidad GDG (Google Developers Group) para la comunidad de desarrolladores. Cada uno de los eventos está organizado por la comunidad local, y este año será un esfuerzo comun con Buenos Aires, el resto del pais, y el Google Business Group."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Buenos Aires"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "WorkShop"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Conoce Nuestros Temas"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
# - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
# - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
